distances, indexes = knr.kneighbors([[50]])
# plt.scatter(train_input, train_output)
# plt.scatter(train_input[indexes],train_output[indexes],marker= 'D')
# plt.scatter(50,1033, marker= '^')
# plt.xlabel('length')
# plt.ylabel('weight')
# plt.show()